[config]
default_to_workspace = false

[env]

[tasks.sort-toml]
args = ["fmt", "--option", "reorder_keys=true"]
command = "taplo"
install_crate = { crate_name = "taplo-cli", binary = "cargo", test_arg = [
  "taplo",
  "--help",
] }


[tasks.test]
args = [
  "nextest",
  "run",
  "--workspace",
  "--status-level",
  "all",
  "--test-threads=1",
]
command = "cargo"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
  "nextest",
  "--help",
] }

[tasks.nextest]
args = ["nextest", "${@}", "--workspace"]
command = "cargo"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
  "nextest",
  "--help",
] }

[tasks.run]
command = "cargo"
args = ["run", "--release", "${@}"]
