[package]
edition.workspace = true
license.workspace = true
name = "shared"
publish.workspace = true
version = "0.1.0"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
